### ISSUE TITLE
Bug: "unable to generate webapp bundle: focalboard: unable to read webapp bundle"

### ISSUE THREAD

**Issue by MarkWieczorek** [mattermost/mattermost-plugin-boards#24]
## Steps to reproduce the behavior

I downloaded the file `mattermost-plugin-boards-v9.0.0.tar.gz`, uncompressed it in the plugins directory and set the correct permissions for the folder. After restarting the server, the plugin doesn't load, and gives the following error

```
Unable to activate plugin","caller":"app/plugin.go:171","plugin_id":"focalboard","bundle_path":"plugins/boards","error":"unable to generate webapp bundle: focalboard: unable to copy webapp bundle directory: focalboard: stat plugins/focalboard/webapp/dist: no such file or directory
```

This is the only plugin that I am having problems installing.

## Expected behavior

I would expect the plugin to load.

**Comment by MarkWieczorek** [comment]
I think that the problem was that I needed to install the file `mattermost-plugin-boards-v9.0.0-linux-amd64.tar.gz ` instead.

Sorry, but I was just following the instructions on the readme!

**Comment by tmotyl** [comment]
I have the same issue even if I download the `mattermost-plugin-boards-v9.0.0-linux-amd64.tar.gz` 
Seems like the board plugin still expect the path plugins/focalboard to exist.
